Repository AY2324S2-CS2113-F15-2/tp, pull requests merged in 2024-04, with the labels that each got.

#92 Progress bar finishing touches
  docs/UserGuide.md
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/user/User.java
  src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Labels: priority.High

#93 Add developer guide for Hydration and Hydration List UML
  docs/DeveloperGuide.md
  docs/HydrationListClassDiagram.png
  docs/HydrationListClassDiagram.puml
  src/main/java/seedu/lifetrack/system/parser/ParserHydration.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/HydrationListTest.java
Labels: priority.High

#95 tidy progress bar output, add file update for calories and hydration progress
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/user/User.java
  src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Labels: type.Task, priority.High

#94 error handling
  docs/DeveloperGuide.md
  docs/HydrationDeleteDiagram.png
  docs/HydrationDeleteDiagram.puml
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/system/parser/ParserHydration.java
Labels: priority.High

#97 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#98 Add javadocs for Calories
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java
  src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
Labels: type.Task, priority.High

#100 Edit user UserGuide
  docs/UserGuide.md
Labels: type.Task, priority.High

#102 Add sequence diagram into Developer guide
  docs/CaloriesAddEntrySeqDiagram.puml
  docs/CaloriesListSequenceDiagram.puml
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#108 Replace API with Manual Calculation
  src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/ui/UserUi.java
  src/main/java/seedu/lifetrack/user/User.java
  src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Labels: priority.High, type.Enhancement, type.Bug, severity.High

#110 Edit UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#111 remove help command expected output, add more planned features
  docs/UserGuide.md
Labels: type.Task, priority.High

#112 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#153 Add entryID into Class CalorieList
  src/main/java/seedu/lifetrack/Entry.java
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/parser/ParserHydration.java
  src/main/java/seedu/lifetrack/system/parser/ParserSleep.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
  src/main/java/seedu/lifetrack/ui/CalorieListUi.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/HydrationListTest.java
  src/test/java/seedu/lifetrack/ParserCaloriesTest.java
  src/test/java/seedu/lifetrack/ParserHydrationTest.java
  src/test/java/seedu/lifetrack/ParserSleepTest.java
Labels: priority.High, type.Story, type.Enhancement

#154 Add distinction between calories output feature
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/ui/CalorieListUi.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
Labels: priority.High, type.Story, type.Enhancement

#158 Add sleep id into sleep print list
  docs/UserGuide.md
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/ui/SleepListUi.java
  src/test/java/seedu/lifetrack/SleepListTest.java
Labels: priority.Medium, type.Enhancement

#161 Add sort entries by date feature
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/ui/CalorieListUi.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
Labels: type.Task, priority.High, type.Story

#167 Add PPP for rex
  docs/team/rexyyong.md
Labels: type.Task, priority.High

#168 Fix Bugs from PE-D and add user update command
  docs/UserGuide.md
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/user/User.java
  src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Labels: priority.High

#170 add first draft of PPP
  docs/UserGuide.md
  docs/team/owx0130.md
Labels: priority.High, task.Admin

#173 Edit developer guide for calories list feature
  docs/CaloriesListClassDiagram.puml
  docs/CaloriesListSequenceDiagram.puml
  docs/DeveloperGuide.md
  docs/diagrams/CaloriesListClassDiagram.png
  docs/diagrams/CaloriesListSequenceDiagram.png
Labels: type.Task, priority.High, task.Admin

#175 Code cleanup
  src/main/java/seedu/lifetrack/calories/Activity.java
  src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
Labels: priority.Medium, task.Admin

#183 Add class diagram for sleep, hydration, calories and user.
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/assets/ArchitectureDiagram.png
  docs/assets/CaloriesAddEntrySeqDiagram.png
  docs/assets/CaloriesListClassDiagram.png
  docs/assets/CaloriesListSequenceDiagram.png
  docs/assets/HydrationDeleteDiagram.png
  docs/assets/HydrationListClassDiagram.png
  docs/assets/SleepAddSeqDiagram.jpg
  docs/assets/SleepDeleteSeqDiagram.jpg
  docs/assets/SleepListSeqDiagram.jpg
  docs/assets/UserCalculateCaloriesSeqDiagram.png
  docs/assets/calories.png
  docs/assets/caloriesDeleteUML.jpg
  docs/assets/hydration.png
  docs/assets/sleep.png
  docs/assets/user.png
  docs/diagrams/ArchitectureDiagram.png
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CaloriesAddEntrySeqDiagram.puml
  docs/diagrams/CaloriesListClassDiagram.puml
  docs/diagrams/CaloriesListSequenceDiagram.puml
  docs/diagrams/HydrationDeleteDiagram.puml
  docs/diagrams/HydrationListClassDiagram.puml
  docs/diagrams/UserCalculateCaloriesSeqDiagram.puml
  docs/diagrams/calories.puml
  docs/diagrams/hydration.puml
  docs/diagrams/sleep.puml
  docs/diagrams/user.puml
Labels: type.Task, priority.High, task.Admin

#185 Add design description for calories component in developer guide
  docs/DeveloperGuide.md
  docs/assets/caloriesComponent.png
  docs/diagrams/calories_component.puml
Labels: type.Task, priority.High, task.Admin

#184 Add 3 day Summary of Calories, Sleep and Hydration
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/ui/UserUi.java
  src/main/java/seedu/lifetrack/user/User.java
  src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Labels: priority.Medium

#201 complete sleep DP
  docs/DeveloperGuide.md
  docs/assets/SleepAddSeqDiagram.png
  docs/diagrams/SleepAddSeqDiagram.puml
Labels: type.Task, priority.Medium

#217 Cleared bugs assigned to me from internal testing
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserSleep.java
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/ui/UserUi.java
  src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
Labels: priority.High

#219 Added JUnit Test Cases for User Class
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/test/java/seedu/lifetrack/ParserUserTest.java
Labels: type.Task, priority.Medium

#218 Edit filehandler
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/calories.png
  docs/assets/caloriesComponent.png
  docs/assets/calories_component.png
  docs/assets/hydration.png
  docs/assets/sleep.png
  docs/diagrams/calories.puml
  docs/diagrams/calories_component.puml
  docs/diagrams/hydration.puml
  docs/diagrams/sleep.puml
  src/main/java/seedu/lifetrack/Entry.java
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/system/exceptions/FileHandlerException.java
  src/main/java/seedu/lifetrack/system/exceptions/FileHandlerExceptionMessage.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/storage/CaloriesFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
  src/main/java/seedu/lifetrack/system/storage/HydrationFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/SleepFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/UserFileHandler.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/user/User.java
  src/test/java/seedu/lifetrack/ParserCaloriesTest.java
  src/test/java/seedu/lifetrack/SleepListTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#220 Find function
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/parser/ParserHydration.java
  src/main/java/seedu/lifetrack/ui/CalorieListUi.java
  src/main/java/seedu/lifetrack/ui/HydrationListUI.java
  src/main/java/seedu/lifetrack/ui/Ui.java
Labels: type.Enhancement

#221 small bugfix for calories input
  src/main/java/seedu/lifetrack/system/storage/CaloriesFileHandler.java
Labels: type.Task, priority.High

#222 Add ability to read in names from users with special characters in their name
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
Labels: priority.High, type.Enhancement

#224 Update UG
  docs/UserGuide.md
Labels: priority.High

#223 final enhancements to app
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/test/java/seedu/lifetrack/ParserCaloriesTest.java
Labels: priority.Medium, type.Enhancement

#246 Fix internal testing issue for Rex
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/ui/CalorieListUi.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/SleepListTest.java
Labels: priority.High, type.Bug

#247 Update DG for User Details
  docs/DeveloperGuide.md
  docs/assets/UserClassDiagram.png
  docs/assets/UserDetailsSequenceDiagram.png
  docs/diagrams/UserClassDiagram.puml
  docs/diagrams/UserDetailsSequenceDiagram.puml
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/user/User.java
Labels: priority.Medium

#248 Fix small Gradle Error
  docs/DeveloperGuide.md
  src/test/java/seedu/lifetrack/SleepListTest.java
Labels: priority.High

#249 Edit Userguide based bug fixes in pr #246
  docs/UserGuide.md
Labels: type.Task, priority.High

#250 Add JUnit tests for filehandler
  sample-data/caloriesTestData.txt
  sample-data/hydrationTestData.txt
  sample-data/sleepTestData.txt
  sample-data/userTestData.txt
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/system/exceptions/FileHandlerExceptionMessage.java
  src/main/java/seedu/lifetrack/system/storage/CaloriesFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
  src/main/java/seedu/lifetrack/system/storage/HydrationFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/SleepFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/UserFileHandler.java
  src/main/java/seedu/lifetrack/user/User.java
  src/test/java/seedu/lifetrack/CaloriesFileHandlerTest.java
  src/test/java/seedu/lifetrack/HydrationFileHandlerTest.java
  src/test/java/seedu/lifetrack/SleepFileHandlerTest.java
  src/test/java/seedu/lifetrack/UserFileHandlerTest.java
Labels: priority.Medium, type.Enhancement

#260 Fix bugs raised from peer testing
  docs/UserGuide.md
  sample-data/sleepTestData.txt
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/ui/CalorieListUi.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
Labels: priority.High, type.Bug

#262 Fix bug for calorie list sorting, sleep list and hydration list
  docs/UserGuide.md
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
Labels: type.Task, priority.High, type.Bug

#263 fixed sleep fail to add issue
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
Labels: priority.High, type.Bug

#266 Edit ug for calories, general and command summary
  docs/UserGuide.md
Labels: priority.High, task.Admin

#268 Edit developer guide appendix
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#272 Update UG to include expected outputs
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
Labels: priority.High

#264 Final changes
  docs/CaloriesListClassDiagram.png
  docs/UserGuide.md
  docs/team/owx0130.md
  sample-data/caloriesTestData.txt
  sample-data/sleepTestData.txt
  src/main/java/seedu/lifetrack/Entry.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationEntry.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/system/exceptions/FileHandlerExceptionMessage.java
  src/main/java/seedu/lifetrack/system/storage/CaloriesFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
  src/main/java/seedu/lifetrack/system/storage/HydrationFileHandler.java
  src/main/java/seedu/lifetrack/system/storage/SleepFileHandler.java
  src/main/java/seedu/lifetrack/user/User.java
  src/test/java/seedu/lifetrack/CaloriesFileHandlerTest.java
  src/test/java/seedu/lifetrack/HydrationFileHandlerTest.java
  src/test/java/seedu/lifetrack/SleepFileHandlerTest.java
  src/test/java/seedu/lifetrack/SleepListTest.java
  src/test/java/seedu/lifetrack/UserFileHandlerTest.java
Labels: priority.Medium, type.Enhancement
