Repository AY2324S2-CS2113-F15-2/tp, pull requests merged in 2024-03, with the labels that each got.

#25 Add JUnit test for Exiting the App
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/parser/Parser.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/DukeTest.java
  src/test/java/seedu/lifetrack/InputTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#28 Add addEntry JUnit test for valid input
  src/main/java/seedu/lifetrack/activity/Activity.java
  src/main/java/seedu/lifetrack/calorielist/CalorieList.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
Labels: type.Task, priority.High

#38 Add liquids in
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/liquids/Liquid.java
  src/main/java/seedu/lifetrack/liquids/beverage/Beverage.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/Entry.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidList.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/parser/ParserLiquid.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/InputTest.java
  src/test/java/seedu/lifetrack/LifeTrackTest.java
Labels: priority.High

#39 Add Food, InputEntry and OutputEntry classes for calorie tracking
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/calories/Activity.java
  src/main/java/seedu/lifetrack/calories/Calorie.java
  src/main/java/seedu/lifetrack/calories/Food.java
  src/main/java/seedu/lifetrack/calories/activity/Activity.java
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/calories/calorielist/Entry.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java
  src/main/java/seedu/lifetrack/liquids/Beverage.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidEntry.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidList.java
  src/main/java/seedu/lifetrack/system/Ui.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/parser/ParserLiquid.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/InputTest.java
  src/test/java/seedu/lifetrack/LifeTrackTest.java
Labels: type.Task, priority.High

#41 add assertions for parseCaloriesInput
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
Labels: type.Task, priority.High

#43 Add more exception handling for Class ParserCalories.java
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/parser/ParserLiquid.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/LifeTrackTest.java
Labels: type.Task, priority.High

#48 make ParserCalories more OOP-like, re-organised JUnit tests
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/LifeTrackTest.java
  src/test/java/seedu/lifetrack/LiquidListTest.java
  src/test/java/seedu/lifetrack/ParserCaloriesTest.java
  src/test/java/seedu/lifetrack/ParserLiquidTest.java
  src/test/java/seedu/lifetrack/UITest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#45 Add logger
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidList.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
Labels: type.Task, priority.Low

#53 Final Changes to v1.1 Release
  META-INF/MANIFEST.MF
  src/main/java/seedu/lifetrack/ui/Ui.java
Labels: priority.High

#55 set authors for original writers of JUnit test code
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/LiquidListTest.java
  src/test/java/seedu/lifetrack/ParserLiquidTest.java
Labels: priority.Medium, task.Admin

#56 add JUnit tests for ParserCalories, relocate ParserCalories error messages
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/calories/Food.java
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/test/java/seedu/lifetrack/LiquidListTest.java
  src/test/java/seedu/lifetrack/ParserCaloriesTest.java
  src/test/java/seedu/lifetrack/ParserLiquidTest.java
Labels: type.Task, priority.Medium

#58 Move UI out of Liquid Class
  .gitignore
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidList.java
  src/main/java/seedu/lifetrack/ui/LiquidListUI.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/LiquidListTest.java
Labels: priority.Medium

#59 Fix logger
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidList.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java
  src/main/java/seedu/lifetrack/ui/CalorieListUi.java
Labels: priority.Low, type.Bug

#60 Add Sleep Feature
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/sleep/Sleep.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java
  src/main/java/seedu/lifetrack/system/parser/ParserSleep.java
  src/main/java/seedu/lifetrack/ui/SleepListUi.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/ParserSleepTest.java
  src/test/java/seedu/lifetrack/SleepListTest.java
  src/test/java/seedu/lifetrack/UITest.java
Labels: type.Task, priority.High

#67 Tidy up hydration exception messages
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserLiquid.java
  src/test/java/seedu/lifetrack/ParserLiquidTest.java
Labels: type.Task, priority.High

#70 Add DG details for ParserCalories
  .gitignore
  docs/DeveloperGuide.md
Labels: priority.Medium, task.Admin

#69 Add file storage capability, change inheritance for Sleep class
  src/main/java/seedu/lifetrack/Entry.java
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/calories/calorielist/CalorieList.java
  src/main/java/seedu/lifetrack/calories/calorielist/Entry.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationList.java
  src/main/java/seedu/lifetrack/liquids/Beverage.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidEntry.java
  src/main/java/seedu/lifetrack/liquids/liquidlist/LiquidList.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepList.java
  src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputException.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/parser/ParserHydration.java
  src/main/java/seedu/lifetrack/system/parser/ParserSleep.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
  src/main/java/seedu/lifetrack/ui/HydrationListUI.java
  src/main/java/seedu/lifetrack/ui/LiquidListUI.java
  src/main/java/seedu/lifetrack/ui/SleepListUi.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/HydrationListTest.java
  src/test/java/seedu/lifetrack/LiquidListTest.java
  src/test/java/seedu/lifetrack/ParserCaloriesTest.java
  src/test/java/seedu/lifetrack/ParserHydrationTest.java
  src/test/java/seedu/lifetrack/SleepListTest.java
  src/test/java/seedu/lifetrack/UITest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#72 update help command output and exception messages
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/ParserHydrationTest.java
Labels: priority.Medium, type.Enhancement

#73 Add a User Class and Calories Needed calculator
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/main/java/seedu/lifetrack/user/User.java
  src/main/java/seedu/lifetrack/user/usergoals/UserGoals.java
  src/test/java/seedu/lifetrack/UITest.java
Labels: priority.High, severity.Medium

#79 Added developer guide for the API
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#80 implement file storage for User
  src/main/java/seedu/lifetrack/LifeTrack.java
  src/main/java/seedu/lifetrack/system/parser/ParserUser.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
  src/main/java/seedu/lifetrack/user/User.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#82 Update DG
  docs/DeveloperGuide.md
  docs/caloriesDeleteUML.jpg
Labels: type.Task, priority.High

#83 Add date format for Calories, Hydration and Sleep
  src/main/java/seedu/lifetrack/Entry.java
  src/main/java/seedu/lifetrack/calories/calorielist/InputEntry.java
  src/main/java/seedu/lifetrack/calories/calorielist/OutputEntry.java
  src/main/java/seedu/lifetrack/hydration/hydrationlist/HydrationEntry.java
  src/main/java/seedu/lifetrack/sleep/sleeplist/SleepEntry.java
  src/main/java/seedu/lifetrack/system/exceptions/ErrorMessages.java
  src/main/java/seedu/lifetrack/system/exceptions/InvalidInputExceptionMessage.java
  src/main/java/seedu/lifetrack/system/parser/ParserCalories.java
  src/main/java/seedu/lifetrack/system/parser/ParserHydration.java
  src/main/java/seedu/lifetrack/system/parser/ParserSleep.java
  src/main/java/seedu/lifetrack/system/storage/FileHandler.java
  src/main/java/seedu/lifetrack/ui/Ui.java
  src/test/java/seedu/lifetrack/CalorieListTest.java
  src/test/java/seedu/lifetrack/HydrationListTest.java
  src/test/java/seedu/lifetrack/ParserCaloriesTest.java
  src/test/java/seedu/lifetrack/ParserHydrationTest.java
  src/test/java/seedu/lifetrack/ParserSleepTest.java
  src/test/java/seedu/lifetrack/SleepListTest.java
Labels: priority.High, type.Enhancement
